#!/bin/sh
### BEGIN INIT INFO
# Provides: oscam
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop service oscam
# Description: oscam
### END INIT INFO
 
DAEMON=/usr/local/bin/oscam
PIDFILE=/var/run/oscam.pid
DAEMON_OPTS="-p 1024 -w 5 -r 2 -B ${PIDFILE}"
 
test -x ${DAEMON} || exit 0
 
. /lib/lsb/init-functions
 
case "$1" in
    start)
   log_daemon_msg "Starting OScam..."
   /sbin/start-stop-daemon --start --quiet --background  --exec ${DAEMON} -- ${DAEMON_OPTS}
   log_end_msg $?
    ;;
  stop)
   log_daemon_msg "Stopping OScam..."
   /sbin/start-stop-daemon --stop --exec ${DAEMON}
   log_end_msg $?
    ;;
  restart)
   $0 stop
   $0 start
    ;;
  force-reload)
   $0 stop
   /bin/kill -9 `pidof oscam`
   /usr/bin/killall -9 oscam
   $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/oscam {start|stop|restart|force-reload}"
    exit 1
    ;;
esac
